import type { LanguagePreference } from "./api";
import { createContext, createElement, useContext, type ReactNode } from "react";

export type Locale = "zh-CN" | "zh-TW" | "en";
export type TranslationVariables = Record<string, string | number>;

const en = {
  overview: "Overview", providers: "Providers", settings: "Settings", refresh: "Refresh",
  route: "Route", active: "Active", inactive: "Inactive", protected: "Protected", loadingRoute: "Loading route", activate: "Activate", deactivate: "Deactivate", light: "Light", dark: "Dark",
  activateRoute: "Activate route", deactivateRoute: "Deactivate route", openNavigation: "Open navigation", closeNavigation: "Close navigation", routeControls: "Route controls", navigation: "Codex Route navigation", home: "Codex Route home", workspaceView: "Workspace view",
  workspaceRoutes: "Workspace routes", workspaces: "Workspaces", workspacesDescription: "Manage and configure your routing workspaces.", workspaceRules: "Workspace rules", configureRoutes: "Configure routes", hideRouteSettings: "Hide route settings",
  settingsDescription: "Configure how Codex Route starts, appears, and routes traffic.",
  startupBehavior: "Startup behavior", startupBehaviorDescription: "Control when Codex Route starts automatically.",
  interfacePreferences: "Interface preferences", interfacePreferencesDescription: "Customize the appearance and language.",
  routeSettings: "Route settings", routeSettingsDescription: "Define how Codex Route connects and operates.",
  defaultRoute: "Default route", defaultRouteDescription: "Used when a session has no known workspace rule.",
  routePort: "Route port", routePortDescription: "Local listener port used the next time Route starts.",
  launchAtLogin: "Launch at login", launchAtLoginDescription: "Start Codex Route automatically when you sign in.",
  closeToTray: "Close window to tray", closeToTrayDescription: "Keep Codex Route running when the window is closed.",
  language: "Language", languageDescription: "Choose the language used by the interface and tray.",
  theme: "Theme", themeDescription: "Choose the appearance used by the interface.",
  system: "Follow system", simplifiedChinese: "简体中文", traditionalChinese: "繁體中文", english: "English",
  chooseProvider: "Choose provider", saveChanges: "Save changes", changesAppliedTogether: "Changes are applied together.",
  workspaceNote: "Workspace-specific routes override the default provider. Port changes apply after the next Route activation.",
  portValidation: "Port must be an integer between 1 and 65535.", retry: "Retry", loadingWorkspace: "Loading workspace…", workspacePathRequired: "Workspace path is required.", chooseProviderForWorkspace: "Choose a provider for this workspace.",
  providersDescription: "Choose the provider Route uses for new sessions.", providersPageDescription: "Manage your connection providers.", importProviders: "Import providers from cc-switch",
  close: "Close", cancel: "Cancel", done: "Done", import: "Import", current: "Current", useProvider: "Use provider",
  noProviders: "No providers yet", loadingProviders: "Loading providers", noWorkspaceRules: "No workspace rules",
  addProviderFirst: "Add a provider first.", noActiveWorkspaces: "No active Codex workspaces",
  workspace: "Workspace", providerRoute: "Provider route", folderUnavailable: "folder unavailable",
  ambiguousSessionMetadata: "ambiguous session metadata", useDefault: "Use default", useDefaultRoute: "Use default route", selectProviderRoute: "Select provider route", sessions: "sessions", session: "session", threads: "threads", thread: "thread", activeWorkspace: "{{count}} active workspace", activeWorkspaces: "{{count}} active workspaces", newSessionsUse: "New sessions will use {{provider}}.", routeStatus: "Route status",
  diagnostics: "Diagnostics", diagnosticsEyebrow: "DIAGNOSTICS", recentClientEvents: "Recent client events", healthEventsDescription: "Route and provider health events will appear here.", filterDiagnostics: "Filter diagnostics", closeDiagnostics: "Close diagnostics", noDiagnostics: "No diagnostics", clear: "Clear", allSeverities: "All severities",
  errors: "Errors", warnings: "Warnings", info: "Info", openDiagnostics: "Open diagnostics", copy: "Copy", copied: "Copied", copyDiagnostic: "Copy diagnostic {{code}}", openProviders: "Open Providers", openWorkspaceRules: "Open Workspace rules", openRuntime: "Open Runtime",
  chooseWorkspaceFolder: "Choose workspace folder", chooseWorkspacePath: "Choose or enter an absolute path",
  removeRule: "Remove workspace rule", removeRuleConfirm: "Remove the route for {{workspace}}?", editRule: "Edit rule", newRule: "New rule", addRule: "Add rule", closeWorkspaceRules: "Close workspace rules",
  save: "Save", remove: "Remove", provider: "Provider", workspacePath: "Workspace path",
  importFromCcSwitch: "Import from cc-switch", scanningCcSwitch: "Scanning cc-switch…", importComplete: "Import complete",
  importSelected: "Import selected ({{count}})", selectAll: "Select all", onConflict: "On conflict",
  skipExisting: "Skip existing", replaceExisting: "Replace existing", importWithNewId: "Import with new ID",
  alreadyImported: "Already imported", noImportableProviders: "No importable Codex providers found", configuredProviders: "Configured providers", availableCcSwitchProviders: "Available cc-switch providers", retryScan: "Retry scan", selectedCount: "{{count}} selected", unavailableConfigurations: "{{count}} unavailable configuration", unavailableConfigurationsPlural: "{{count}} unavailable configurations", importing: "Importing…", importSummary: "Imported {{imported}} · Replaced {{replaced}} · Renamed {{renamed}} · Skipped {{skipped}} · Rejected {{rejected}}",
  importFailed: "Could not complete the import", routeUnavailable: "Route unavailable", startRoute: "Start Route", stopRoute: "Stop Route", noListener: "No listener", ready: "Ready", starting: "Starting…", recovering: "Recovering…", failed: "Failed", needsAttention: "Needs attention", stopped: "Stopped", stopRouteAction: "Stop Route", startRouteAction: "Start Route",
  providerNone: "Provider: none", providerNamed: "Provider: {{name}}", defaultRouteProvider: "Default route provider", showCodexRoute: "Show Codex Route", quitCodexRoute: "Quit Codex Route", localRoute: "LOCAL ROUTE", localListenerDescription: "Local listener for Codex provider routing.", listener: "Listener", configuration: "Configuration", managedByCodexRoute: "Managed by Codex Route", notManaged: "Not managed", routeUrl: "Route URL", unavailable: "Unavailable", port: "Port", externalModification: "External modification", externalConfigWarning: "Codex config changed outside Codex Route. Deactivation is blocked to protect it.", runtime: "Runtime", closeImport: "Close import dialog", editRouteFor: "Edit route for {{workspace}}", removeRouteFor: "Remove route for {{workspace}}",
} as const;

type TranslationKey = keyof typeof en;
type Dictionary = Record<TranslationKey, string>;

const zhCN: Dictionary = {
  ...en,
  overview: "概览", providers: "提供商", settings: "设置", refresh: "刷新", route: "Route", active: "运行中", inactive: "未运行", protected: "已保护", loadingRoute: "正在加载 Route",
  activateRoute: "启用 Route", deactivateRoute: "停用 Route", activate: "启用", deactivate: "停用", openNavigation: "打开导航", closeNavigation: "关闭导航", workspaceRoutes: "工作区路由", workspaces: "工作区", workspacesDescription: "管理和配置你的路由工作区。", configureRoutes: "配置路由", hideRouteSettings: "隐藏路由设置", settingsDescription: "配置 Codex Route 的启动方式、外观和流量路由。", startupBehavior: "启动行为", startupBehaviorDescription: "控制 Codex Route 何时自动启动。", interfacePreferences: "界面偏好", interfacePreferencesDescription: "自定义界面外观和语言。", routeSettings: "Route 设置", routeSettingsDescription: "定义 Codex Route 的连接和运行方式。",
  defaultRoute: "默认路由", defaultRouteDescription: "会话没有匹配的工作区规则时使用。", routePort: "Route 端口", routePortDescription: "下次启动 Route 时使用的本地监听端口。", launchAtLogin: "登录时启动", launchAtLoginDescription: "登录系统时自动启动 Codex Route。", closeToTray: "关闭窗口时缩到托盘", closeToTrayDescription: "关闭窗口后让 Codex Route 继续在后台运行。", language: "语言", languageDescription: "选择界面和托盘使用的语言。", theme: "主题", themeDescription: "选择界面的显示主题。", system: "跟随系统", simplifiedChinese: "简体中文", traditionalChinese: "繁體中文", english: "English", light: "亮色", dark: "深色", chooseProvider: "选择提供商", saveChanges: "保存更改", changesAppliedTogether: "所有更改将一起应用。", workspaceNote: "工作区路由会覆盖默认提供商。端口更改将在下次启用 Route 后生效。", portValidation: "端口必须是 1 到 65535 之间的整数。", retry: "重试", loadingWorkspace: "正在加载工作区…", providersDescription: "选择 Route 用于新会话的提供商。", providersPageDescription: "管理你的连接提供商。", importProviders: "从 cc-switch 导入提供商", close: "关闭", cancel: "取消", done: "完成", current: "当前", useProvider: "使用提供商", noProviders: "暂无提供商", loadingProviders: "正在加载提供商", noWorkspaceRules: "暂无工作区规则", addProviderFirst: "请先添加提供商。", noActiveWorkspaces: "没有活动的 Codex 工作区", workspace: "工作区", providerRoute: "提供商路由", folderUnavailable: "文件夹不可用", ambiguousSessionMetadata: "会话元数据有歧义", useDefault: "使用默认", routeStatus: "Route 状态", diagnostics: "诊断", noDiagnostics: "暂无诊断信息", clear: "清除", allSeverities: "所有级别", errors: "错误", warnings: "警告", info: "信息", openDiagnostics: "打开诊断", copy: "复制", copied: "已复制", chooseWorkspaceFolder: "选择工作区文件夹", chooseWorkspacePath: "选择或输入绝对路径", removeRule: "移除工作区规则", editRule: "编辑规则", newRule: "新建规则", addRule: "添加规则", save: "保存", remove: "移除", provider: "提供商", workspacePath: "工作区路径", importFromCcSwitch: "从 cc-switch 导入", scanningCcSwitch: "正在扫描 cc-switch…", importComplete: "导入完成", importSelected: "导入选中的 {{count}} 项", selectAll: "全选", onConflict: "冲突处理", skipExisting: "跳过已有项", replaceExisting: "替换已有项", importWithNewId: "使用新 ID 导入", alreadyImported: "已导入", noImportableProviders: "没有可导入的 Codex 提供商", importFailed: "导入未完成", routeUnavailable: "Route 不可用", startRoute: "启动 Route", stopRoute: "停止 Route", providerNone: "提供商：无", providerNamed: "提供商：{{name}}", showCodexRoute: "显示 Codex Route", quitCodexRoute: "退出 Codex Route",
  workspaceRules: "工作区规则", import: "导入", defaultRouteProvider: "默认路由提供商", routeControls: "Route 控制", navigation: "Codex Route 导航", home: "Codex Route 首页", workspaceView: "工作区视图", workspacePathRequired: "工作区路径不能为空。", chooseProviderForWorkspace: "请选择此工作区的提供商。", useDefaultRoute: "使用默认路由", selectProviderRoute: "选择提供商路由", session: "会话", sessions: "会话", thread: "线程", threads: "线程", activeWorkspace: "{{count}} 个活动工作区", activeWorkspaces: "{{count}} 个活动工作区", newSessionsUse: "新会话将使用 {{provider}}。", diagnosticsEyebrow: "诊断", recentClientEvents: "最近的客户端事件", healthEventsDescription: "Route 和提供商的健康事件会显示在这里。", filterDiagnostics: "筛选诊断信息", closeDiagnostics: "关闭诊断", copyDiagnostic: "复制诊断信息 {{code}}", openProviders: "打开提供商", openWorkspaceRules: "打开工作区规则", openRuntime: "打开运行时", removeRuleConfirm: "移除 {{workspace}} 的路由？", closeWorkspaceRules: "关闭工作区规则", configuredProviders: "已配置的提供商", availableCcSwitchProviders: "可用的 cc-switch 提供商", retryScan: "重试扫描", selectedCount: "已选择 {{count}} 项", unavailableConfigurations: "{{count}} 个不可用配置", unavailableConfigurationsPlural: "{{count}} 个不可用配置", importing: "正在导入…", importSummary: "已导入 {{imported}} · 已替换 {{replaced}} · 已重命名 {{renamed}} · 已跳过 {{skipped}} · 已拒绝 {{rejected}}", noListener: "没有监听器", ready: "就绪", starting: "正在启动…", recovering: "正在恢复…", failed: "失败", needsAttention: "需要注意", stopped: "已停止", stopRouteAction: "停止 Route", startRouteAction: "启动 Route", localRoute: "本地 Route", localListenerDescription: "Codex 提供商路由的本地监听器。", listener: "监听器", configuration: "配置", managedByCodexRoute: "由 Codex Route 管理", notManaged: "未管理", routeUrl: "Route URL", unavailable: "不可用", port: "端口", externalModification: "外部修改", externalConfigWarning: "Codex 配置已在 Codex Route 外部修改。为保护配置，无法停用。", runtime: "运行时", closeImport: "关闭导入对话框", editRouteFor: "编辑 {{workspace}} 的路由", removeRouteFor: "移除 {{workspace}} 的路由",
};

const zhTW: Dictionary = {
  ...zhCN,
  overview: "總覽", providers: "提供商", settings: "設定", refresh: "重新整理", active: "執行中", inactive: "未執行", protected: "已保護", loadingRoute: "正在載入 Route", activate: "啟用", deactivate: "停用", activateRoute: "啟用 Route", deactivateRoute: "停用 Route", openNavigation: "開啟導覽", closeNavigation: "關閉導覽", workspaceRoutes: "工作區路由", workspaces: "工作區", workspacesDescription: "管理和設定你的路由工作區。", configureRoutes: "設定路由", hideRouteSettings: "隱藏路由設定", settingsDescription: "設定 Codex Route 的啟動方式、外觀與流量路由。", defaultRoute: "預設路由", defaultRouteDescription: "工作階段沒有符合的工作區規則時使用。", routePort: "Route 連接埠", routePortDescription: "下次啟動 Route 時使用的本機監聽連接埠。", launchAtLogin: "登入時啟動", launchAtLoginDescription: "登入系統時自動啟動 Codex Route。", closeToTray: "關閉視窗時縮到系統匣", closeToTrayDescription: "關閉視窗後讓 Codex Route 繼續在背景執行。", language: "語言", languageDescription: "選擇介面與系統匣使用的語言。", theme: "主題", themeDescription: "選擇介面的顯示主題。", system: "跟隨系統", simplifiedChinese: "簡體中文", traditionalChinese: "繁體中文", light: "淺色", dark: "深色", chooseProvider: "選擇提供商", saveChanges: "儲存變更", changesAppliedTogether: "所有變更將一起套用。", workspaceNote: "工作區路由會覆蓋預設提供商。連接埠變更將在下次啟用 Route 後生效。", portValidation: "連接埠必須是 1 到 65535 之間的整數。", retry: "重試", loadingWorkspace: "正在載入工作區…", providersDescription: "選擇 Route 用於新工作階段的提供商。", providersPageDescription: "管理你的連線提供商。", importProviders: "從 cc-switch 匯入提供商", close: "關閉", cancel: "取消", done: "完成", current: "目前", useProvider: "使用提供商", noProviders: "尚無提供商", loadingProviders: "正在載入提供商", noWorkspaceRules: "尚無工作區規則", addProviderFirst: "請先新增提供商。", noActiveWorkspaces: "沒有作用中的 Codex 工作區", workspace: "工作區", providerRoute: "提供商路由", folderUnavailable: "資料夾無法使用", ambiguousSessionMetadata: "工作階段中繼資料有歧義", useDefault: "使用預設", routeStatus: "Route 狀態", diagnostics: "診斷", noDiagnostics: "尚無診斷資訊", clear: "清除", allSeverities: "所有層級", errors: "錯誤", warnings: "警告", info: "資訊", openDiagnostics: "開啟診斷", copy: "複製", copied: "已複製", chooseWorkspaceFolder: "選擇工作區資料夾", chooseWorkspacePath: "選擇或輸入絕對路徑", removeRule: "移除工作區規則", editRule: "編輯規則", newRule: "新增規則", addRule: "新增規則", save: "儲存", remove: "移除", provider: "提供商", workspacePath: "工作區路徑", importFromCcSwitch: "從 cc-switch 匯入", scanningCcSwitch: "正在掃描 cc-switch…", importComplete: "匯入完成", importSelected: "匯入選取的 {{count}} 項", selectAll: "全選", onConflict: "衝突處理", skipExisting: "略過已有項目", replaceExisting: "取代已有項目", importWithNewId: "使用新 ID 匯入", alreadyImported: "已匯入", noImportableProviders: "沒有可匯入的 Codex 提供商", importFailed: "匯入未完成", routeUnavailable: "Route 無法使用", startRoute: "啟動 Route", stopRoute: "停止 Route", providerNone: "提供商：無", providerNamed: "提供商：{{name}}", showCodexRoute: "顯示 Codex Route", quitCodexRoute: "結束 Codex Route",
  workspaceRules: "工作區規則", import: "匯入", defaultRouteProvider: "預設路由提供商", routeControls: "Route 控制", navigation: "Codex Route 導覽", home: "Codex Route 首頁", workspaceView: "工作區檢視", workspacePathRequired: "工作區路徑為必填。", chooseProviderForWorkspace: "請為此工作區選擇提供商。", useDefaultRoute: "使用預設路由", selectProviderRoute: "選擇提供商路由", session: "工作階段", sessions: "工作階段", thread: "執行緒", threads: "執行緒", activeWorkspace: "{{count}} 個作用中的工作區", activeWorkspaces: "{{count}} 個作用中的工作區", newSessionsUse: "新工作階段將使用 {{provider}}。", diagnosticsEyebrow: "診斷", recentClientEvents: "最近的用戶端事件", healthEventsDescription: "Route 與提供商的健康事件會顯示在這裡。", filterDiagnostics: "篩選診斷資訊", closeDiagnostics: "關閉診斷", copyDiagnostic: "複製診斷資訊 {{code}}", openProviders: "開啟提供商", openWorkspaceRules: "開啟工作區規則", openRuntime: "開啟執行環境", removeRuleConfirm: "移除 {{workspace}} 的路由？", closeWorkspaceRules: "關閉工作區規則", configuredProviders: "已設定的提供商", availableCcSwitchProviders: "可用的 cc-switch 提供商", retryScan: "重試掃描", selectedCount: "已選取 {{count}} 項", unavailableConfigurations: "{{count}} 個不可用設定", unavailableConfigurationsPlural: "{{count}} 個不可用設定", importing: "正在匯入…", importSummary: "已匯入 {{imported}} · 已取代 {{replaced}} · 已重新命名 {{renamed}} · 已略過 {{skipped}} · 已拒絕 {{rejected}}", noListener: "沒有監聽器", ready: "就緒", starting: "正在啟動…", recovering: "正在復原…", failed: "失敗", needsAttention: "需要注意", stopped: "已停止", stopRouteAction: "停止 Route", startRouteAction: "啟動 Route", localRoute: "本機 Route", localListenerDescription: "Codex 提供商路由的本機監聽器。", listener: "監聽器", configuration: "設定", managedByCodexRoute: "由 Codex Route 管理", notManaged: "未管理", routeUrl: "Route URL", unavailable: "無法使用", port: "連接埠", externalModification: "外部修改", externalConfigWarning: "Codex 設定已在 Codex Route 外部修改。為保護設定，無法停用。", runtime: "執行環境", closeImport: "關閉匯入對話框", editRouteFor: "編輯 {{workspace}} 的路由", removeRouteFor: "移除 {{workspace}} 的路由", startupBehavior: "啟動行為", startupBehaviorDescription: "控制 Codex Route 何時自動啟動。", interfacePreferences: "介面偏好", interfacePreferencesDescription: "自訂介面外觀與語言。", routeSettings: "Route 設定", routeSettingsDescription: "定義 Codex Route 的連線與執行方式。",
};

export type Translator = (key: TranslationKey, variables?: TranslationVariables) => string;

const defaultTranslator = createTranslator("en");
const I18nContext = createContext<Translator>(defaultTranslator);

export function I18nProvider({ translator, children }: { translator: Translator; children: ReactNode }) {
  return createElement(I18nContext.Provider, { value: translator }, children);
}

export function useTranslation(): Translator {
  return useContext(I18nContext);
}

export function resolveLocale(preference: LanguagePreference, systemLocale = navigator.language): Locale {
  if (preference !== "system") return preference;
  const normalized = systemLocale.trim().replace(/_/g, "-").toLowerCase();
  if (normalized.startsWith("zh-tw") || normalized.startsWith("zh-hk") || normalized.startsWith("zh-mo")) return "zh-TW";
  if (normalized.startsWith("zh-cn") || normalized.startsWith("zh-sg") || normalized.startsWith("zh-my")) return "zh-CN";
  return "en";
}

export function createTranslator(locale: Locale): Translator {
  const dictionary = locale === "zh-CN" ? zhCN : locale === "zh-TW" ? zhTW : en;
  return (key, variables = {}) => dictionary[key].replace(/\{\{(\w+)\}\}/g, (token, name) => String(variables[name] ?? token));
}
